baseURL = "https://www.mznuruliman.or.id/"
languageCode = "id-id"
title = "Majelis Zikir Nurul Iman"
theme = "hargo"
publishDir = "docs"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Products"
  URL = "products"
  weight = 1
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 1
  
  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3
  
  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions"
  weight = 4
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
custom_styles = ["scss/custom.scss"]
logo = "images/mzni.png"
home = "Home"
# Meta data
description = "Yayasan Majelis Zikir Nurul Iman"
author = "Sulaeman"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAOqwExEbG3Lcm0aNZLfUCvr6C9wA10H54&libraries=places"
mapLatitude = "-7.248239"
mapLongitude = "107.808853"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "-"
email = "demo@email.com"
location = "Garut"
# copyright
copyright = "Yayasan Majelis Zikir Nurul Iman | Copyright &copy; 2020"

  # Navigation
  [params.navigation]
  enable = false

    [params.navigation.cart]
    enable = false

  # Footer
  [params.footer]
  enable = false

    [params.footer.important_links]
    enable = false

    [params.footer.connect]
    enable = false

    [params.footer.contact]
    enable = false

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "#"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"
  
  [[params.social]]
  icon = "ti-youtube"
  link = "#"
  
  [[params.social]]
  icon = "ti-instagram"
  link = "#"
  
  [[params.social]]
  icon = "ti-pinterest"
  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io